module.exports = {
  docs: [
    'Home',
    {
      type: 'category',
      label: 'Java学习',
      items: [
         'SSM三层架构',
         'Java语言概述',
         'Java的三大特性',
         'JVM与JAVA体系结构',
      ],
    },

    {
      type: 'category',
      label: '工具收集',
      items: [
        '电报开源情报工具汇总',
      ],
    },
    {
      type: 'category',
      label: 'Leecode面经',
      items: [
         'Leecode01',
      ],
    },

    {
      type: 'category',
      label: '高效工作',
      items: [
        'Windows初始化与软件推荐',
        '为什么你需要一个知识库',
        'Docusaurus极简部署指南',
        'Hugo极简搭建指南',
        '如何在iPad上运行VSCode',
        '使用Markdown进行高效写作',
        '团队知识库搭建记录-DokuWiki',
        '个人知识库极简搭建指南-VuePress',
        '用树莓派架设云打印服务器',
        '文章排版规范',
        '基于docsify搭建个人Wiki',
        '用Graphviz绘制关系图',
        '博客转至GitBook',
        'RSS-高效率的阅读方式',
        '把回忆放心交给GooglePhotos',
        '构建知识管理系统',
        '回归博客',
        'VSCode生产力指南-环境配置',
        'VSCode生产力指南-JupyterNotebook',
        '在浏览器上运行VSCode（旧）',
        '如何配一台电脑',
        '用reveal.js制作幻灯片',
      ],
    },
    {
      type: 'category',
      label: '软件开发',
      items: [
        'CSS学习笔记',
        'HTML学习笔记',
        'JavaScript学习笔记',
        'Docker简易指南',
        'DockerCompose-更优雅的打开方式',
        '自适应网页设计',
        'Git学习笔记',
      ],
    },

    {
      type: 'category',
      label: '生活经历',
      items: [
      ],
    },

    {
      type: 'category',
      label: '小技巧',
      items: [
        '如何为公众号文章增加特效',
        '如何在Linux下使用微信',
        '如何打印出手写效果的文字',
        '如何从乐曲中分离音轨',
        '如何高效制作幻灯片',
        '卡片式写作',
        'npm和Yarn换源加速国内访问',
        'Vue.js小技巧',
        '正则表达式实用语句',
        'LaTeX希腊字母对照表',
        'GitHub改Host',
        'Linux用户操作',
        'MSI主板开启虚拟化的方法',
        'Git配置代理',
        '删除GitHub仓库中某个文件夹',
        '定制SublimeText3',
        '如何保存易逝的文字',
        //'Excel批量激活链接并转为图片',
        '用Vercel加速Pages服务',
        'Doxygen注释规范',
        'AltiumDesigner安装库文件',
        'CentOS配置OhMyZsh',
        '如何快速制作一个启动盘',
        '使用VSCode进行远程开发',
        'Node.js和npm的安装与卸载（MacOS）',
        //'Bash基础',
        //'Linux基础（CentOS）',
        //'从零搭建视觉开发环境（Docker-Linux）',
      ],
    },

  ],
};
